<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertials.xacro"/>
    <xacro:include filename="materials.xacro"/>

    <!-- Define robot constants https://navigation.ros.org/setup_guides/urdf/setup_urdf.html -->
    <xacro:property name="yaml_file" value="$(find description_bauda_akm)/config/vehicle.yaml" />
    <xacro:property name="dict" value="${load_yaml(yaml_file)}"/> 
    <xacro:property name="base_mass" value="${dict['base'][mass]}" /> 
    <xacro:property name="base_length" value="${dict['base'][length]}" /> 
    <xacro:property name="base_width" value="${dict['base'][width]}" /> 
    <xacro:property name="base_height" value="${dict['base'][height]}" /> 
    <xacro:property name="wheel_mass" value="${dict['wheel'][mass]}" /> 
    <xacro:property name="wheel_radius" value="${dict['wheel'][radius]}" /> 
    <xacro:property name="wheel_width" value="${dict['wheel'][width]}" /> 
    <xacro:property name="wheel_ygap" value="${dict['wheel'][ygap]}" /> 
    <xacro:property name="wheel_rear_xoff" value="${dict['wheel'][rear_xoff]}" /> 
    <xacro:property name="wheel_front_xoff" value="${dict['wheel'][front_xoff]}" /> 

    <!-- BASE LINK -->
    <link name="base_link" />

    <!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="base_footprint" />

    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-${wheel_rear_xoff} 0 0"/>
    </joint>
    <link name="chassis">
        <visual>
            <origin xyz="${base_length / 2} 0 ${base_height / 2}"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${base_length / 2} 0 ${base_height / 2}"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}">
            <origin xyz="${base_length / 2} 0 ${base_height / 2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>


</robot>