<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="bauda_diff">

    <joint name="base_lidar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar_base"/>
        <origin xyz="${lidar_x} ${lidar_y} ${lidar_z + lidar_base_height / 2}" rpy="0 0 0"/>
    </joint>

    <link name="lidar_base">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_base_height}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_base_height}" radius="${lidar_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="lidar_joint" type="continuous">
        <parent link="lidar_base"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${lidar_base_height / 2 + lidar_top_height / 2}" rpy="0 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_top_height}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_top_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_top_height}" radius="${lidar_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
         
    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <!-- <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.02</stddev>
                </noise> -->
                <scan>
                    <vertical>
                        <samples>32</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.53529248</min_angle>
                        <max_angle>0.18622663</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.06</min>
                    <max>70</max>
                    <resolution>0.02</resolution>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>--ros-args -r ~/out:=/scan</argument>
                </ros>
                <output_type>sensor_msgs/PointCloud2</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>