<?xml version="1.0"?>
<robot name="wheel" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:include filename="materials.xacro"/>
    <xacro:include filename="inertials.xacro"/>

    <xacro:macro name="wheel" params="left_or_right rear_or_front">
    <joint name="${rear_or_front}_${left_or_right}_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${rear_or_front}_${left_or_right}_wheel"/>
        <origin xyz="0 0.175 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    <link name="${rear_or_front}_${left_or_right}_wheel_link">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
        </geometry>
        <material name="yellow" />
        </visual>
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
        </geometry>
        </collision>
        <xacro:solid_cylinder_inertial 
            rpy="0 0 0" xyz="0 0 0"
            mass="${steer_mass}"
            radius="${steer_radius}" length="${steer_thickness}" />
    </link>

    <joint name="${name}_steer_joint" type="revolute">
        <parent link="${parent}_link"/>
        <child link="${name}_steer_link"/>
        <origin xyz="${base_length/2-axle_offset} 0 ${steer_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${steer_effort}"
                lower="${-180.0 * deg_to_rad}" upper="${180.0 * deg_to_rad}"
                velocity="${steer_velocity}"/>
    </joint>

    <transmission name="${name}_steer_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="${name}_steer_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </actuator>
        <joint name="${name}_steer_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
    </transmission>

    <gazebo reference="${name}_steer_link">
        <material>Gazebo/Yellow</material>
    </gazebo>
    </xacro:macro>

</robot>