controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    akm_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

akm_cont:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
    front_wheels_names: [right_steering_joint, left_steering_joint]

    wheelbase: 3.24644
    front_wheel_track: 2.12321
    rear_wheel_track: 1.76868
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05


# joint_broad:
#   ros__parameters: