controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    akm_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    # lidar_joint_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

akm_cont:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: false
    rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
    front_wheels_names: [right_steering_joint, left_steering_joint]

    wheelbase: 0.2
    front_wheel_track: 0.41
    rear_wheel_track: 0.41
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05


# lidar_joint_controller:
#   ros__parameters:
#     joints:
#       - lidar_joint