gazebo_ros_control:
  pid_gains:
    rear_left_wheel_joint:
      p: 0.06
      i: 0.0
      d: 0.0
    rear_right_wheel_joint:
      p: 0.06
      i: 0.0
      d: 0.0
    left_steering_joint:
      p: 0.06
      i: 0.0
      d: 0.0
    right_steering_joint:
      p: 0.06
      i: 0.0
      d: 0.0