base:
  mass: 1.0
  length: 0.3
  width: 0.3
  height: 0.15

wheel:
  mass: 0.05
  radius: 0.05
  width: 0.01
  ygap: 0.005
  rear_xoff: 0.05
  distance_between_axes: 0.25

steering:
  limit_angle: 0.3
  limit_effort: 100
  limit_velocity: 100

# camera:
#   x:
#   y:
#   z: