teleop_twist_joy_node:
  ros__parameters:
    wheelbase: 0.2

    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Left thumb stick horizontal
      steering: 3
    scale_angular:
      steering: 0.5

    require_enable_button: false
    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
